org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

runtime_include_emi=true
runtime_include_ei=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.248
loader_version_range=[1,)

## Dependencies
grandpower_version=3.0.0
modern_industrialization_version=2.5.6
tesseract_version=1.12.16-1.21.1
guideme_version=21.1.13
emi_version=1.1.24+1.21.1
modularui_version=3.3.1-SNAPSHOT
##Ranges
modern_industrialization_version_range=[2.5.6, 2.6-)
tesseract_version_range=[1.12.16-, 1.13-)
emi_version_range=[1.1.24, 1.2-)
modularui_version_range=[3.3.1-SNAPSHOT,)


mod_id=mipp
mod_name=MI++
mod_license=GPL-3.0-or-later
mod_version=0.1.1b
mod_group_id=dev.waldq.mipp
mod_github=https://github.com/waldq/MIplusplus
mod_authors=waldq
mod_description=Various features for Modern Industrialization